// <auto-generated />
using System;
using GrpcGreeter.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GrpcGreeter.Migrations
{
    [DbContext(typeof(LeaveDbContext))]
    [Migration("20210205012249_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("GrpcGreeter.Entity.ApplicationLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ApplicantId")
                        .HasColumnType("integer");

                    b.Property<int>("ApproverId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LeaveType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ApproverId");

                    b.ToTable("ApplicationLeaves");
                });

            modelBuilder.Entity("GrpcGreeter.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FirstWorkDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("GrpcGreeter.Entity.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Phone")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Personnels");
                });

            modelBuilder.Entity("GrpcGreeter.Entity.ApplicationLeave", b =>
                {
                    b.HasOne("GrpcGreeter.Entity.Employee", "Applicant")
                        .WithMany("Applicants")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrpcGreeter.Entity.Employee", "Approver")
                        .WithMany("Approvers")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Approver");
                });

            modelBuilder.Entity("GrpcGreeter.Entity.Employee", b =>
                {
                    b.HasOne("GrpcGreeter.Entity.Personnel", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("GrpcGreeter.Entity.Employee", b =>
                {
                    b.Navigation("Applicants");

                    b.Navigation("Approvers");
                });
#pragma warning restore 612, 618
        }
    }
}
